export enum Event {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGOUT = "LOGOUT",

  GUEST_ACQUIRED_LOCK = "GUEST_ACQUIRED_LOCK",

  HOST_END_CONVERSATION = "HOST_END_CONVERSATION",
  GUEST_END_CONVERSATION = "GUEST_END_CONVERSATION",

  HOST_CLOSE_RECEPTION = "HOST_CLOSE_RECEPTION",
  OPEN_RECEPTION = "OPEN_RECEPTION",

  HOST_REFRESH = "HOST_REFRESH",
  GUEST_REFRESH = "GUEST_REFRESH",

  HOST_BROWSER_CLOSE = "HOST_BROWSER_CLOSE",
  GUEST_BROWSER_CLOSE = "GUEST_BROWSER_CLOSE",

  HOST_CONNECTION_LOSS = "HOST_CONNECTION_LOSS",
  GUEST_CONNECTION_LOSS = "GUEST_CONNECTION_LOSS",

  TIMEOUT = "TIMEOUT",
  MAX_DURATION = "MAX_DURATION",

  NEW_LOGIN_CONTINUE = "NEW_LOGIN_CONTINUE",
}